
"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { FolderOpen, Save, FileCode2, Command as CmdIcon } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

export default function LocalManagerPage() {
    const [path, setPath] = useState("/Volumes/MOVESPEED/下载/AIcode/Mywebsite/KunlunGrowth/website");
    const [status, setStatus] = useState("Idle");
    const { toast } = useToast();

    const handleCreatePost = async () => {
        setStatus("Generating & Writing...");
        try {
            // Mock content generation for now, real implementation would call LLM
            const dummyContent = `
export const metadata = {
  title: 'AI SEO Automation Guide 2026',
  description: 'How to automate SEO using AI Agents like SEO Velocity.',
};

export default function Post() {
  return (
    <article className="prose lg:prose-xl mx-auto py-10">
      <h1>AI SEO Automation Guide 2026</h1>
      <p>This post was auto-generated by SEO Velocity Agent directly into your codebase.</p>
    </article>
  );
}
            `;

            const resp = await fetch("/api/local/write", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({
                    type: "write_blog",
                    filePath: "ai-seo-guide/page.tsx", // Relative to app/blog
                    content: dummyContent
                })
            });

            const data = await resp.json();
            if (data.success) {
                toast({ title: "Success", description: "Created file: app/blog/ai-seo-guide/page.tsx" });
                setStatus("Success");
            } else {
                toast({ title: "Error", description: data.error, variant: "destructive" });
                setStatus("Error: " + data.error);
            }
        } catch (e: any) {
            setStatus("Failed");
            toast({ title: "Failed", description: e.message, variant: "destructive" });
        }
    };

    return (
        <div className="container py-8 max-w-4xl space-y-6">
            <h1 className="text-3xl font-bold">Local Codebase Manager</h1>
            <p className="text-muted-foreground">Manage your local Next.js project directly.</p>

            <Card>
                <CardHeader><CardTitle>Target Project</CardTitle></CardHeader>
                <CardContent className="space-y-4">
                    <div className="flex gap-4">
                        <Input value={path} onChange={(e) => setPath(e.target.value)} />
                        <Button disabled><FolderOpen className="mr-2 h-4 w-4" /> Load</Button>
                    </div>
                </CardContent>
            </Card>

            <div className="grid grid-cols-2 gap-4">
                <Card className="hover:border-primary cursor-pointer transition-all" onClick={handleCreatePost}>
                    <CardHeader>
                        <CardTitle className="flex items-center gap-2"><FileCode2 className="h-5 w-5" /> Auto-Write Blog Post</CardTitle>
                    </CardHeader>
                    <CardContent>
                        <p className="text-sm text-muted-foreground">
                            Generate "AI SEO Guide 2026" and save directly to <code>app/blog/</code> folder.
                        </p>
                        <div className="mt-4 text-xs font-mono bg-secondary p-2 rounded">
                            Status: {status}
                        </div>
                    </CardContent>
                </Card>
            </div>
        </div>
    );
}
