import { ProductTier } from "@/types/subscriptions";

export const SUBSCRIPTION_TIERS: ProductTier[] = [
  {
    name: "Creator",
    id: "tier-creator",
    productId: "prod_63JTQmsUcQrlZe94IL76fI",
    priceMonthly: "$19",
    description: "Perfect for content creators and social media managers.",
    features: [
      "50 Video Generations / mo",
      "Up to 15 seconds per video",
      "720p Resolution",
      "3 Reference Files per generation",
      "Standard Processing Speed",
      "Community Support",
    ],
    featured: false,
    discountCode: "",
  },
  {
    name: "Professional",
    id: "tier-pro",
    productId: "prod_6rOJtTwlyjsH9AVuSzh8aR",
    priceMonthly: "$79",
    description: "For agencies and professional video producers.",
    features: [
      "300 Video Generations / mo",
      "Up to 15 seconds per video",
      "1080p Resolution",
      "12 Reference Files per generation",
      "Priority Processing",
      "Multi-Language Lip-Sync",
      "Advanced Motion Control",
      "Email Support",
    ],
    featured: true,
    discountCode: "",
  },
  {
    name: "Studio",
    id: "tier-studio",
    productId: "prod_3qPYksZMtk94wQsdkgajrJ",
    priceMonthly: "$299",
    description: "Enterprise-grade video production at scale.",
    features: [
      "Unlimited Video Generations",
      "Up to 15 seconds per video",
      "2K Resolution",
      "12 Reference Files per generation",
      "Fastest Processing",
      "API Access",
      "White-label Options",
      "Dedicated Account Manager",
    ],
    featured: false,
    discountCode: "",
  },
];

export const CREDITS_TIERS: ProductTier[] = [
  {
    name: "Quick Start",
    id: "tier-25-videos",
    productId: "prod_MqcjVo0Bpx0rbYmHVlrh2",
    priceMonthly: "$29",
    description: "25 one-time video generations.",
    creditAmount: 25,
    features: [
      "25 Video Generations",
      "Never expires",
      "All resolution options",
      "Full reference file support",
    ],
    featured: false,
    discountCode: "",
  },
  {
    name: "Power Pack",
    id: "tier-100-videos",
    productId: "prod_4ICkTovEC6o9QY6UuL3aI0",
    priceMonthly: "$99",
    description: "100 one-time video generations.",
    creditAmount: 100,
    features: [
      "100 Video Generations",
      "Never expires",
      "Priority processing",
      "Best value per video",
    ],
    featured: true,
    discountCode: "",
  },
  {
    name: "Studio Bundle",
    id: "tier-500-videos",
    productId: "prod_3b3oyQtIJA3eaMIHLNjyCc",
    priceMonthly: "$399",
    description: "500 one-time video generations.",
    creditAmount: 500,
    features: [
      "500 Video Generations",
      "Never expires",
      "Fastest processing",
      "Maximum savings",
    ],
    featured: false,
    discountCode: "",
  },
];
